services:
  postgres:
    image: postgres:15
    container_name: postgres_aluno_online_p3b
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres_aluno_online_p3b
    ports:
      - "5433:5432"
    networks:
      - aluno_online_network
    restart: unless-stopped

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver_aluno_online
    depends_on:
      - postgres
    ports:
      - "15432:8978"
    networks:
      - aluno_online_network
    restart: unless-stopped

networks:
  aluno_online_network:
    driver: bridge